CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(15) NOT NULL CHECK (role IN ('ADMIN', 'COMPANY', 'JOB_SEEKER', 'HUMAN_RESOURCE')),
    is_profile_completed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (username)
);

CREATE TABLE admins (
    id BIGINT NOT NULL,
    totp_secret VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_admins_users FOREIGN KEY (id) REFERENCES users
);

CREATE TABLE job_seekers (
    id BIGINT NOT NULL,
    full_name VARCHAR(50),
    academic_year VARCHAR(10),
    disability_type VARCHAR(10) CHECK (disability_type IN ('VISUAL', 'HEARING', 'MOBILITY', 'COGNITIVE')),
    education_level VARCHAR(20) CHECK (education_level IN ('HIGH_SCHOOL', 'COLLEGE_STUDENT', 'BACHELOR', 'MASTER', 'DOCTORATE')),
    cv_document_path VARCHAR(100),
    pp_image_path VARCHAR(100),
    address VARCHAR(150),
    about_me VARCHAR(500),
    job_type_preference VARCHAR(255) CHECK (job_type_preference IN ('FULL_TIME', 'FREELANCE', 'CONTRACT', 'REMOTE', 'INTERNSHIP')),
    PRIMARY KEY (id),
    CONSTRAINT FK_seekers_users FOREIGN KEY (id) REFERENCES users
);

CREATE TABLE companies (
    id BIGINT NOT NULL,
    company_name VARCHAR(50),
    industry_type VARCHAR(15) CHECK (industry_type IN ('TECHNOLOGY', 'HEALTHCARE', 'EDUCATION', 'FINANCE', 'ECOMMERCE', 'MEDIA', 'OTHERS')),
    company_description VARCHAR(500),
    logo_image_path VARCHAR(100),
    address VARCHAR(150),
    website_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    instagram_url VARCHAR(255),
    twitter_url VARCHAR(255),
    youtube_url VARCHAR(255),
    agree_to_terms BOOLEAN,
    PRIMARY KEY (id),
    CONSTRAINT FK_companies_users FOREIGN KEY (id) REFERENCES users
);

CREATE TABLE human_resources (
    id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    full_name VARCHAR(50),
    contact VARCHAR(15),
    pp_image_path VARCHAR(100),
    PRIMARY KEY (id),
    CONSTRAINT FK_hr_companies FOREIGN KEY (company_id) REFERENCES companies,
    CONSTRAINT FK_hr_users FOREIGN KEY (id) REFERENCES users
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT NOT NULL,
    title VARCHAR(50) NOT NULL,
    job_description VARCHAR(1000),
    job_type VARCHAR(10) NOT NULL CHECK (job_type IN ('FULL_TIME', 'FREELANCE', 'CONTRACT', 'REMOTE', 'INTERNSHIP')),
    publication_status VARCHAR(10) NOT NULL CHECK (publication_status IN ('OPEN', 'CLOSED')),
    minimum_education VARCHAR(20) CHECK (minimum_education IN ('HIGH_SCHOOL', 'COLLEGE_STUDENT', 'BACHELOR', 'MASTER', 'DOCTORATE')),
    min_years_experience INTEGER,
    salary NUMERIC(12, 2),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    registration_deadline TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT FK_jobs_companies FOREIGN KEY (company_id) REFERENCES companies
);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id BIGINT NOT NULL,
    job_seeker_id BIGINT NOT NULL,
    application_status VARCHAR(15) NOT NULL CHECK (application_status IN ('UNDER_REVIEW', 'ACCEPTED', 'DECLINED')),
    cover_letter VARCHAR(500),
    hr_notes VARCHAR(500),
    applied_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (job_seeker_id, job_id),
    CONSTRAINT FK_apps_jobs FOREIGN KEY (job_id) REFERENCES jobs,
    CONSTRAINT FK_apps_seekers FOREIGN KEY (job_seeker_id) REFERENCES job_seekers
);

CREATE TABLE job_compatible_disabilities (
    job_id BIGINT NOT NULL,
    disability_type VARCHAR(10) NOT NULL CHECK (disability_type IN ('VISUAL', 'HEARING', 'MOBILITY', 'COGNITIVE')),
    CONSTRAINT FK_disability_jobs FOREIGN KEY (job_id) REFERENCES jobs
);

CREATE TABLE job_seeker_certifications (
    job_seeker_id BIGINT NOT NULL,
    certification_file_path VARCHAR(100) NOT NULL,
    CONSTRAINT FK_certs_seekers FOREIGN KEY (job_seeker_id) REFERENCES job_seekers
);

CREATE TABLE job_seeker_skills (
    job_seeker_id BIGINT NOT NULL,
    skill VARCHAR(50) NOT NULL,
    CONSTRAINT FK_skills_seekers FOREIGN KEY (job_seeker_id) REFERENCES job_seekers
);

CREATE TABLE logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_username VARCHAR(50) NOT NULL,
    actor_role VARCHAR(15) NOT NULL,
    action VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);