CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    actor_role VARCHAR(15) NOT NULL,
    action VARCHAR(50) NOT NULL,
    actor_username VARCHAR(50) NOT NULL,
    description VARCHAR(75) NOT NULL
);

CREATE TABLE admins (
    id BIGINT NOT NULL PRIMARY KEY,
    totp_secret VARCHAR(100) NOT NULL
);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applied_at TIMESTAMP(6) NOT NULL,
    job_id BIGINT NOT NULL,
    job_seeker_id BIGINT NOT NULL,
    application_status VARCHAR(15) NOT NULL CHECK (application_status IN ('UNDER_REVIEW','ACCEPTED','DECLINED')),
    hr_notes VARCHAR(1000),
    UNIQUE (job_seeker_id, job_id)
);

CREATE TABLE companies (
    id BIGINT NOT NULL PRIMARY KEY,
    industry_type VARCHAR(15) CHECK (industry_type IN ('TECHNOLOGY','HEALTHCARE','EDUCATION','FINANCE','ECOMMERCE','MEDIA','OTHERS')),
    company_name VARCHAR(50),
    logo_image_path VARCHAR(100),
    address VARCHAR(150),
    company_description VARCHAR(1000),
    website_url VARCHAR(255)
);

CREATE TABLE human_resources (
    id BIGINT NOT NULL PRIMARY KEY,
    company_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL,
    full_name VARCHAR(50),
    contact VARCHAR(15)
);

CREATE TABLE job_compatible_disabilities (
    job_id BIGINT NOT NULL,
    disability_type VARCHAR(10) NOT NULL CHECK (disability_type IN ('VISUAL','HEARING','MOBILITY','COGNITIVE'))
);

CREATE TABLE job_seeker_certifications (
    job_seeker_id BIGINT NOT NULL,
    certification_file_path VARCHAR(100) NOT NULL
);

CREATE TABLE job_seeker_skills (
    job_seeker_id BIGINT NOT NULL,
    skill VARCHAR(50) NOT NULL
);

CREATE TABLE job_seekers (
    id BIGINT NOT NULL PRIMARY KEY,
    disability_type VARCHAR(10) CHECK (disability_type IN ('VISUAL','HEARING','MOBILITY','COGNITIVE')),
    education_level VARCHAR(20) CHECK (education_level IN ('HIGH_SCHOOL','COLLEGE_STUDENT','BACHELOR','MASTER','DOCTORATE')),
    full_name VARCHAR(50),
    cv_document_path VARCHAR(100),
    pp_image_path VARCHAR(100),
    address VARCHAR(150),
    about_me VARCHAR(1000)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    registration_deadline TIMESTAMP(6),
    min_years_experience INTEGER,
    salary NUMERIC(12,2),
    publication_status VARCHAR(10) NOT NULL CHECK (publication_status IN ('OPEN','CLOSED')),
    minimum_education VARCHAR(20) CHECK (minimum_education IN ('HIGH_SCHOOL','COLLEGE_STUDENT','BACHELOR','MASTER','DOCTORATE')),
    title VARCHAR(50) NOT NULL,
    job_description VARCHAR(1000)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(15) NOT NULL CHECK (role IN ('ADMIN','COMPANY','JOB_SEEKER','HUMAN_RESOURCE')),
    is_profile_completed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

ALTER TABLE admins
    ADD CONSTRAINT fk_admin_user
    FOREIGN KEY (id) REFERENCES users(id);

ALTER TABLE applications
    ADD CONSTRAINT fk_application_job
    FOREIGN KEY (job_id) REFERENCES jobs(id);

ALTER TABLE applications
    ADD CONSTRAINT fk_application_job_seeker
    FOREIGN KEY (job_seeker_id) REFERENCES job_seekers(id);

ALTER TABLE companies
    ADD CONSTRAINT fk_company_user
    FOREIGN KEY (id) REFERENCES users(id);

ALTER TABLE human_resources
    ADD CONSTRAINT fk_hr_company
    FOREIGN KEY (company_id) REFERENCES companies(id);

ALTER TABLE human_resources
    ADD CONSTRAINT fk_hr_user
    FOREIGN KEY (id) REFERENCES users(id);

ALTER TABLE job_compatible_disabilities
    ADD CONSTRAINT fk_disability_job
    FOREIGN KEY (job_id) REFERENCES jobs(id);

ALTER TABLE job_seeker_certifications
    ADD CONSTRAINT fk_certification_job_seeker
    FOREIGN KEY (job_seeker_id) REFERENCES job_seekers(id);

ALTER TABLE job_seeker_skills
    ADD CONSTRAINT fk_skill_job_seeker
    FOREIGN KEY (job_seeker_id) REFERENCES job_seekers(id);

ALTER TABLE job_seekers
    ADD CONSTRAINT fk_job_seeker_user
    FOREIGN KEY (id) REFERENCES users(id);

ALTER TABLE jobs
    ADD CONSTRAINT fk_job_company
    FOREIGN KEY (company_id) REFERENCES companies(id);