-- Table
create table users (
    id bigint generated by default as identity primary key,
    identifier varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) not null check (role in ('JOB_SEEKER','COMPANY','HUMAN_RESOURCE','ADMIN')),
    profile_completed boolean not null
);

create table admins (
    id bigint not null primary key,
    totp_secret varchar(64)
);

create table companies (
    id bigint not null primary key,
    updated_at timestamp(6),
    address varchar(255),
    description varchar(255),
    industry_type varchar(255) check (industry_type in ('TECHNOLOGY','HEALTHCARE','EDUCATION','FINANCE','ECOMMERCE','MEDIA','OTHERS')),
    logo_img_path varchar(255),
    name varchar(255),
    website_url varchar(255)
);

create table job_seekers (
    id bigint not null primary key,
    updated_at timestamp(6),
    about varchar(1000),
    address varchar(255),
    cv_file_path varchar(255),
    disability_type varchar(255) check (disability_type in ('VISUAL','HEARING','MOBILITY','COGNITIVE')),
    education_level varchar(255) check (education_level in ('HIGH_SCHOOL','COLLEGE_STUDENT','BACHELOR','MASTER','DOCTORATE')),
    name varchar(255),
    pp_img_path varchar(255)
);

create table human_resources (
    id bigint not null primary key,
    company_id bigint not null
);

create table jobs (
    id bigint generated by default as identity primary key,
    company_id bigint not null,
    minimum_years_experience integer,
    salary numeric(38,2),
    created_at timestamp(6),
    updated_at timestamp(6),
    registration_deadline timestamp(6),
    description varchar(2000),
    minimum_education varchar(255) check (minimum_education in ('HIGH_SCHOOL','COLLEGE_STUDENT','BACHELOR','MASTER','DOCTORATE')),
    publication_status varchar(255) check (publication_status in ('OPEN','CLOSED')),
    title varchar(255)
);

create table applications (
    id bigint generated by default as identity primary key,
    applied_at timestamp(6),
    job_id bigint not null,
    job_seeker_id bigint not null,
    hr_notes varchar(256),
    status varchar(255) check (status in ('UNDER_REVIEW','ACCEPTED','DECLINED'))
);

create table job_compatible_disabilities (
    job_id bigint not null,
    disability_type varchar(255) not null check (disability_type in ('VISUAL','HEARING','MOBILITY','COGNITIVE')),
    primary key (job_id, disability_type)
);

create table job_seeker_certifications (
    job_seeker_id bigint not null,
    certification_path varchar(255) not null,
    primary key (job_seeker_id, certification_path)
);

create table job_seeker_skills (
    job_seeker_id bigint not null,
    skill varchar(255) not null,
    primary key (job_seeker_id, skill)
);

create table activity_logs (
    id bigint generated by default as identity primary key,
    time_created timestamp(6),
    action varchar(255),
    actor_identifier varchar(255),
    actor_role varchar(255),
    description varchar(255)
);

-- Foreign Key
alter table admins
    add constraint fk_admin_user foreign key (id) references users(id);

alter table companies
    add constraint fk_company_user foreign key (id) references users(id);

alter table job_seekers
    add constraint fk_jobseeker_user foreign key (id) references users(id);

alter table human_resources
    add constraint fk_hr_user foreign key (id) references users(id);

alter table human_resources
    add constraint fk_hr_company foreign key (company_id) references companies(id);

alter table jobs
    add constraint fk_job_company foreign key (company_id) references companies(id);

alter table applications
    add constraint fk_application_job foreign key (job_id) references jobs(id);

alter table applications
    add constraint fk_application_jobseeker foreign key (job_seeker_id) references job_seekers(id);

alter table job_compatible_disabilities
    add constraint fk_disability_job foreign key (job_id) references jobs(id);

alter table job_seeker_certifications
    add constraint fk_cert_jobseeker foreign key (job_seeker_id) references job_seekers(id);

alter table job_seeker_skills
    add constraint fk_skill_jobseeker foreign key (job_seeker_id) references job_seekers(id);
