# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ippl_difability
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# SQL
# spring.jpa.properties.hibernate.hbm2ddl.auto=none
# spring.jpa.properties.hibernate.hbm2ddl.schema_generation_script_source=metadata
# spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql

# File Upload
file.upload-dir = C:/Files/Projects/be-ippl-difability/uploads/
spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 10MB

# JWT
jwt.secret = 883060fa-7d2c-4eb4-a92e-075bb7e2a395
jwt.expiration-ms = 86400000

# Admin
ADMIN_EMAIL = admin@difability.com
ADMIN_PASSWORD = Admin123
ADMIN_TOTP_SECRET = adminotpsecretabcdefg
